//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_SHIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADM_SHIPMENT()
        {
            this.ADM_CONTAINER = new HashSet<ADM_CONTAINER>();
            this.ADM_DISTRIBUTION = new HashSet<ADM_DISTRIBUTION>();
            this.ADM_REPORT_OBSERVATION = new HashSet<ADM_REPORT_OBSERVATION>();
        }
    
        public int SHIP_ID { get; set; }
        public string SHIP_CODE { get; set; }
        public Nullable<int> SHIP_CUS_ID { get; set; }
        public Nullable<int> SHIP_SHIPPER_ID { get; set; }
        public Nullable<int> SHIP_NAV_ID { get; set; }
        public Nullable<int> SHIP_RPTSI_ID { get; set; }
        public Nullable<int> SHIP_RPTSW_ID { get; set; }
        public Nullable<int> SHIP_PORTL_ID { get; set; }
        public Nullable<int> SHIP_PORTD_ID { get; set; }
        public Nullable<int> SHIP_PROD_ID { get; set; }
        public Nullable<int> SHIP_PRO_ID { get; set; }
        public Nullable<int> SHIP_ITEMTY_ID { get; set; }
        public Nullable<int> SHIP_CONTY_ID { get; set; }
        public string SHIP_RPTS_CLIENT { get; set; }
        public string SHIP_NRO_PER { get; set; }
        public string SHIP_BOOKING { get; set; }
        public string SHIP_BL { get; set; }
        public System.DateTime SHIP_DATE_SCHEDULED { get; set; }
        public int SHIP_TOTAL_ITEMS { get; set; }
        public int SHIP_AMOUNT_CONTAINER { get; set; }
        public Nullable<int> SHIP_VESSEL { get; set; }
        public string SHIP_REFERENCE { get; set; }
        public string SHIP_STATE { get; set; }
        public string SHIP_DESCRIPTION { get; set; }
        public string SHIP_OBS_GENERAL { get; set; }
        public string SHIP_OBS_REPORT { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime AUD_DATE_REGISTERED { get; set; }
        public Nullable<System.DateTime> AUD_DATE_LASTUPDATED { get; set; }
        public Nullable<int> AUD_USERID_REGISTERED { get; set; }
        public Nullable<int> AUD_USERID_LASTUPDATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADM_CONTAINER> ADM_CONTAINER { get; set; }
        public virtual ADM_CONTAINER_TYPE ADM_CONTAINER_TYPE { get; set; }
        public virtual ADM_CUSTOMER ADM_CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADM_DISTRIBUTION> ADM_DISTRIBUTION { get; set; }
        public virtual ADM_ITEM_TYPE ADM_ITEM_TYPE { get; set; }
        public virtual ADM_NAVE ADM_NAVE { get; set; }
        public virtual ADM_PORT_DISCHARGE ADM_PORT_DISCHARGE { get; set; }
        public virtual ADM_PORT_LOAD ADM_PORT_LOAD { get; set; }
        public virtual ADM_PRODUCER ADM_PRODUCER { get; set; }
        public virtual ADM_PRODUCT ADM_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADM_REPORT_OBSERVATION> ADM_REPORT_OBSERVATION { get; set; }
        public virtual ADM_RPTS_ITK ADM_RPTS_ITK { get; set; }
        public virtual ADM_RPTS_WAREHOUSE ADM_RPTS_WAREHOUSE { get; set; }
        public virtual ADM_SHIPPER ADM_SHIPPER { get; set; }
    }
}
