//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_ICMEntities : DbContext
    {
        public DB_ICMEntities()
            : base("name=DB_ICMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADM_ACTIVITY> ADM_ACTIVITY { get; set; }
        public virtual DbSet<ADM_CONTAINER> ADM_CONTAINER { get; set; }
        public virtual DbSet<ADM_CONTAINER_TYPE> ADM_CONTAINER_TYPE { get; set; }
        public virtual DbSet<ADM_CUSTOMER> ADM_CUSTOMER { get; set; }
        public virtual DbSet<ADM_DISTRIBUTION> ADM_DISTRIBUTION { get; set; }
        public virtual DbSet<ADM_DISTRIBUTION_PALET> ADM_DISTRIBUTION_PALET { get; set; }
        public virtual DbSet<ADM_ITEM_TYPE> ADM_ITEM_TYPE { get; set; }
        public virtual DbSet<ADM_LOTE> ADM_LOTE { get; set; }
        public virtual DbSet<ADM_NAVE> ADM_NAVE { get; set; }
        public virtual DbSet<ADM_NOTIFICATION> ADM_NOTIFICATION { get; set; }
        public virtual DbSet<ADM_OBSERVATION> ADM_OBSERVATION { get; set; }
        public virtual DbSet<ADM_PHOTO> ADM_PHOTO { get; set; }
        public virtual DbSet<ADM_PHOTO_TYPE> ADM_PHOTO_TYPE { get; set; }
        public virtual DbSet<ADM_PORT_DISCHARGE> ADM_PORT_DISCHARGE { get; set; }
        public virtual DbSet<ADM_PORT_LOAD> ADM_PORT_LOAD { get; set; }
        public virtual DbSet<ADM_PRODUCER> ADM_PRODUCER { get; set; }
        public virtual DbSet<ADM_PRODUCT> ADM_PRODUCT { get; set; }
        public virtual DbSet<ADM_REPORT_OBSERVATION> ADM_REPORT_OBSERVATION { get; set; }
        public virtual DbSet<ADM_ROL> ADM_ROL { get; set; }
        public virtual DbSet<ADM_RPTS_ITK> ADM_RPTS_ITK { get; set; }
        public virtual DbSet<ADM_RPTS_WAREHOUSE> ADM_RPTS_WAREHOUSE { get; set; }
        public virtual DbSet<ADM_SHIPMENT> ADM_SHIPMENT { get; set; }
        public virtual DbSet<ADM_SHIPPER> ADM_SHIPPER { get; set; }
        public virtual DbSet<ADM_USER> ADM_USER { get; set; }
        public virtual DbSet<ADM_USER_MOBILE> ADM_USER_MOBILE { get; set; }
    
        public virtual int WEB_GetAllConfigurationByTableName(string tABLE_NAME)
        {
            var tABLE_NAMEParameter = tABLE_NAME != null ?
                new ObjectParameter("TABLE_NAME", tABLE_NAME) :
                new ObjectParameter("TABLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_GetAllConfigurationByTableName", tABLE_NAMEParameter);
        }
    
        public virtual ObjectResult<WEB_GetAllContainerTypes_Result> WEB_GetAllContainerTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetAllContainerTypes_Result>("WEB_GetAllContainerTypes");
        }
    
        public virtual ObjectResult<WEB_GetAllCustomers_Result> WEB_GetAllCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetAllCustomers_Result>("WEB_GetAllCustomers");
        }
    
        public virtual ObjectResult<string> WEB_GetAllDropDownListForShipmentDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WEB_GetAllDropDownListForShipmentDetails");
        }
    
        public virtual ObjectResult<WEB_GetAllItemTypes_Result> WEB_GetAllItemTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetAllItemTypes_Result>("WEB_GetAllItemTypes");
        }
    
        public virtual ObjectResult<WEB_GetAllReportShipmentsByCustomer_Result> WEB_GetAllReportShipmentsByCustomer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetAllReportShipmentsByCustomer_Result>("WEB_GetAllReportShipmentsByCustomer");
        }
    
        public virtual ObjectResult<WEB_GetAllRoles_Result> WEB_GetAllRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetAllRoles_Result>("WEB_GetAllRoles");
        }
    
        public virtual ObjectResult<WEB_GetAllShipments_Result> WEB_GetAllShipments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetAllShipments_Result>("WEB_GetAllShipments");
        }
    
        public virtual ObjectResult<WEB_GetAllUsers_Result> WEB_GetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetAllUsers_Result>("WEB_GetAllUsers");
        }
    
        public virtual int WEB_GetConfigurationById(Nullable<int> cON_ID, string tB_NAME)
        {
            var cON_IDParameter = cON_ID.HasValue ?
                new ObjectParameter("CON_ID", cON_ID) :
                new ObjectParameter("CON_ID", typeof(int));
    
            var tB_NAMEParameter = tB_NAME != null ?
                new ObjectParameter("TB_NAME", tB_NAME) :
                new ObjectParameter("TB_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_GetConfigurationById", cON_IDParameter, tB_NAMEParameter);
        }
    
        public virtual ObjectResult<WEB_GetContainersByShipmentId_Result> WEB_GetContainersByShipmentId(Nullable<int> sHIP_ID)
        {
            var sHIP_IDParameter = sHIP_ID.HasValue ?
                new ObjectParameter("SHIP_ID", sHIP_ID) :
                new ObjectParameter("SHIP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetContainersByShipmentId_Result>("WEB_GetContainersByShipmentId", sHIP_IDParameter);
        }
    
        public virtual ObjectResult<WEB_GetDetailsByShipmentCode_Result> WEB_GetDetailsByShipmentCode(string sHIP_CODE)
        {
            var sHIP_CODEParameter = sHIP_CODE != null ?
                new ObjectParameter("SHIP_CODE", sHIP_CODE) :
                new ObjectParameter("SHIP_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetDetailsByShipmentCode_Result>("WEB_GetDetailsByShipmentCode", sHIP_CODEParameter);
        }
    
        public virtual ObjectResult<WEB_GetDistributionLoteById_Result> WEB_GetDistributionLoteById(Nullable<int> lOTE_ID)
        {
            var lOTE_IDParameter = lOTE_ID.HasValue ?
                new ObjectParameter("LOTE_ID", lOTE_ID) :
                new ObjectParameter("LOTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetDistributionLoteById_Result>("WEB_GetDistributionLoteById", lOTE_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> WEB_GetExistsShipmentCode(string sHIP_CODE)
        {
            var sHIP_CODEParameter = sHIP_CODE != null ?
                new ObjectParameter("SHIP_CODE", sHIP_CODE) :
                new ObjectParameter("SHIP_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("WEB_GetExistsShipmentCode", sHIP_CODEParameter);
        }
    
        public virtual ObjectResult<WEB_GetInspectionReportByCustomerIdAndNroPer_Result> WEB_GetInspectionReportByCustomerIdAndNroPer(string sHIP_NRO_PER, Nullable<int> sHIP_CUS_ID)
        {
            var sHIP_NRO_PERParameter = sHIP_NRO_PER != null ?
                new ObjectParameter("SHIP_NRO_PER", sHIP_NRO_PER) :
                new ObjectParameter("SHIP_NRO_PER", typeof(string));
    
            var sHIP_CUS_IDParameter = sHIP_CUS_ID.HasValue ?
                new ObjectParameter("SHIP_CUS_ID", sHIP_CUS_ID) :
                new ObjectParameter("SHIP_CUS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetInspectionReportByCustomerIdAndNroPer_Result>("WEB_GetInspectionReportByCustomerIdAndNroPer", sHIP_NRO_PERParameter, sHIP_CUS_IDParameter);
        }
    
        public virtual ObjectResult<WEB_GetLotesByShipmentId_Result> WEB_GetLotesByShipmentId(Nullable<int> sHIP_ID)
        {
            var sHIP_IDParameter = sHIP_ID.HasValue ?
                new ObjectParameter("SHIP_ID", sHIP_ID) :
                new ObjectParameter("SHIP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetLotesByShipmentId_Result>("WEB_GetLotesByShipmentId", sHIP_IDParameter);
        }
    
        public virtual ObjectResult<WEB_GetReferenceByShipmentId_Result> WEB_GetReferenceByShipmentId(Nullable<int> sHIP_ID)
        {
            var sHIP_IDParameter = sHIP_ID.HasValue ?
                new ObjectParameter("SHIP_ID", sHIP_ID) :
                new ObjectParameter("SHIP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetReferenceByShipmentId_Result>("WEB_GetReferenceByShipmentId", sHIP_IDParameter);
        }
    
        public virtual ObjectResult<WEB_GetReportObservationById_Result> WEB_GetReportObservationById(Nullable<int> rPTOBS_ID)
        {
            var rPTOBS_IDParameter = rPTOBS_ID.HasValue ?
                new ObjectParameter("RPTOBS_ID", rPTOBS_ID) :
                new ObjectParameter("RPTOBS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetReportObservationById_Result>("WEB_GetReportObservationById", rPTOBS_IDParameter);
        }
    
        public virtual ObjectResult<WEB_GetReportObservations_Result> WEB_GetReportObservations(Nullable<int> sHIP_ID, Nullable<int> sHIP_CUS_ID)
        {
            var sHIP_IDParameter = sHIP_ID.HasValue ?
                new ObjectParameter("SHIP_ID", sHIP_ID) :
                new ObjectParameter("SHIP_ID", typeof(int));
    
            var sHIP_CUS_IDParameter = sHIP_CUS_ID.HasValue ?
                new ObjectParameter("SHIP_CUS_ID", sHIP_CUS_ID) :
                new ObjectParameter("SHIP_CUS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetReportObservations_Result>("WEB_GetReportObservations", sHIP_IDParameter, sHIP_CUS_IDParameter);
        }
    
        public virtual ObjectResult<WEB_GetShipmentsByDate_Result> WEB_GetShipmentsByDate(Nullable<System.DateTime> sHIP_DATE_SCHEDULED_START)
        {
            var sHIP_DATE_SCHEDULED_STARTParameter = sHIP_DATE_SCHEDULED_START.HasValue ?
                new ObjectParameter("SHIP_DATE_SCHEDULED_START", sHIP_DATE_SCHEDULED_START) :
                new ObjectParameter("SHIP_DATE_SCHEDULED_START", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetShipmentsByDate_Result>("WEB_GetShipmentsByDate", sHIP_DATE_SCHEDULED_STARTParameter);
        }
    
        public virtual ObjectResult<WEB_GetUserByEmail_Result> WEB_GetUserByEmail(string uSER_EMAIL)
        {
            var uSER_EMAILParameter = uSER_EMAIL != null ?
                new ObjectParameter("USER_EMAIL", uSER_EMAIL) :
                new ObjectParameter("USER_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetUserByEmail_Result>("WEB_GetUserByEmail", uSER_EMAILParameter);
        }
    
        public virtual ObjectResult<WEB_GetUserByEmailAndPassword_Result> WEB_GetUserByEmailAndPassword(string uSER_EMAIL, string uSER_PASSWORD)
        {
            var uSER_EMAILParameter = uSER_EMAIL != null ?
                new ObjectParameter("USER_EMAIL", uSER_EMAIL) :
                new ObjectParameter("USER_EMAIL", typeof(string));
    
            var uSER_PASSWORDParameter = uSER_PASSWORD != null ?
                new ObjectParameter("USER_PASSWORD", uSER_PASSWORD) :
                new ObjectParameter("USER_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetUserByEmailAndPassword_Result>("WEB_GetUserByEmailAndPassword", uSER_EMAILParameter, uSER_PASSWORDParameter);
        }
    
        public virtual ObjectResult<WEB_GetUserById_Result> WEB_GetUserById(Nullable<int> uSER_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_GetUserById_Result>("WEB_GetUserById", uSER_IDParameter);
        }
    
        public virtual int WEB_PostDeleteConfiguration(Nullable<int> cON_ID, string tB_NAME)
        {
            var cON_IDParameter = cON_ID.HasValue ?
                new ObjectParameter("CON_ID", cON_ID) :
                new ObjectParameter("CON_ID", typeof(int));
    
            var tB_NAMEParameter = tB_NAME != null ?
                new ObjectParameter("TB_NAME", tB_NAME) :
                new ObjectParameter("TB_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostDeleteConfiguration", cON_IDParameter, tB_NAMEParameter);
        }
    
        public virtual int WEB_PostDeleteLote(Nullable<int> lOTE_ID)
        {
            var lOTE_IDParameter = lOTE_ID.HasValue ?
                new ObjectParameter("LOTE_ID", lOTE_ID) :
                new ObjectParameter("LOTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostDeleteLote", lOTE_IDParameter);
        }
    
        public virtual int WEB_PostDeleteReportObservation(Nullable<int> rPTOBS_ID)
        {
            var rPTOBS_IDParameter = rPTOBS_ID.HasValue ?
                new ObjectParameter("RPTOBS_ID", rPTOBS_ID) :
                new ObjectParameter("RPTOBS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostDeleteReportObservation", rPTOBS_IDParameter);
        }
    
        public virtual int WEB_PostDeleteShipment(string sHIP_CODE)
        {
            var sHIP_CODEParameter = sHIP_CODE != null ?
                new ObjectParameter("SHIP_CODE", sHIP_CODE) :
                new ObjectParameter("SHIP_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostDeleteShipment", sHIP_CODEParameter);
        }
    
        public virtual int WEB_PostDeleteUser(Nullable<int> uSER_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostDeleteUser", uSER_IDParameter);
        }
    
        public virtual int WEB_PostSaveConfiguration(Nullable<int> cON_ID, string cON_DESC, string tB_NAME)
        {
            var cON_IDParameter = cON_ID.HasValue ?
                new ObjectParameter("CON_ID", cON_ID) :
                new ObjectParameter("CON_ID", typeof(int));
    
            var cON_DESCParameter = cON_DESC != null ?
                new ObjectParameter("CON_DESC", cON_DESC) :
                new ObjectParameter("CON_DESC", typeof(string));
    
            var tB_NAMEParameter = tB_NAME != null ?
                new ObjectParameter("TB_NAME", tB_NAME) :
                new ObjectParameter("TB_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveConfiguration", cON_IDParameter, cON_DESCParameter, tB_NAMEParameter);
        }
    
        public virtual int WEB_PostSaveContainer(Nullable<int> cONT_ID, string cONT_CODE, Nullable<int> cONT_SHIP_ID, Nullable<int> cONT_AMOUNT_ITEM, Nullable<decimal> cONT_WEIGHT, string cONT_PREC_ADUANA, string cONT_PREC_LINE, string cONT_PREC_ITK, string cONT_PREC_CUS, string cONT_OBS)
        {
            var cONT_IDParameter = cONT_ID.HasValue ?
                new ObjectParameter("CONT_ID", cONT_ID) :
                new ObjectParameter("CONT_ID", typeof(int));
    
            var cONT_CODEParameter = cONT_CODE != null ?
                new ObjectParameter("CONT_CODE", cONT_CODE) :
                new ObjectParameter("CONT_CODE", typeof(string));
    
            var cONT_SHIP_IDParameter = cONT_SHIP_ID.HasValue ?
                new ObjectParameter("CONT_SHIP_ID", cONT_SHIP_ID) :
                new ObjectParameter("CONT_SHIP_ID", typeof(int));
    
            var cONT_AMOUNT_ITEMParameter = cONT_AMOUNT_ITEM.HasValue ?
                new ObjectParameter("CONT_AMOUNT_ITEM", cONT_AMOUNT_ITEM) :
                new ObjectParameter("CONT_AMOUNT_ITEM", typeof(int));
    
            var cONT_WEIGHTParameter = cONT_WEIGHT.HasValue ?
                new ObjectParameter("CONT_WEIGHT", cONT_WEIGHT) :
                new ObjectParameter("CONT_WEIGHT", typeof(decimal));
    
            var cONT_PREC_ADUANAParameter = cONT_PREC_ADUANA != null ?
                new ObjectParameter("CONT_PREC_ADUANA", cONT_PREC_ADUANA) :
                new ObjectParameter("CONT_PREC_ADUANA", typeof(string));
    
            var cONT_PREC_LINEParameter = cONT_PREC_LINE != null ?
                new ObjectParameter("CONT_PREC_LINE", cONT_PREC_LINE) :
                new ObjectParameter("CONT_PREC_LINE", typeof(string));
    
            var cONT_PREC_ITKParameter = cONT_PREC_ITK != null ?
                new ObjectParameter("CONT_PREC_ITK", cONT_PREC_ITK) :
                new ObjectParameter("CONT_PREC_ITK", typeof(string));
    
            var cONT_PREC_CUSParameter = cONT_PREC_CUS != null ?
                new ObjectParameter("CONT_PREC_CUS", cONT_PREC_CUS) :
                new ObjectParameter("CONT_PREC_CUS", typeof(string));
    
            var cONT_OBSParameter = cONT_OBS != null ?
                new ObjectParameter("CONT_OBS", cONT_OBS) :
                new ObjectParameter("CONT_OBS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveContainer", cONT_IDParameter, cONT_CODEParameter, cONT_SHIP_IDParameter, cONT_AMOUNT_ITEMParameter, cONT_WEIGHTParameter, cONT_PREC_ADUANAParameter, cONT_PREC_LINEParameter, cONT_PREC_ITKParameter, cONT_PREC_CUSParameter, cONT_OBSParameter);
        }
    
        public virtual int WEB_PostSaveForgetPassword(Nullable<int> uSER_ID, string uSER_PASSWORD_GENERATED)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var uSER_PASSWORD_GENERATEDParameter = uSER_PASSWORD_GENERATED != null ?
                new ObjectParameter("USER_PASSWORD_GENERATED", uSER_PASSWORD_GENERATED) :
                new ObjectParameter("USER_PASSWORD_GENERATED", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveForgetPassword", uSER_IDParameter, uSER_PASSWORD_GENERATEDParameter);
        }
    
        public virtual int WEB_PostSaveLote(Nullable<int> lOTE_ID, string lOTE_CODE, Nullable<int> lOTE_AMOUNT_ITEM, Nullable<int> lOTE_ITEMTY_ID, Nullable<int> dIS_SHIP_ID, Nullable<int> dIS_AMOUNT_TOTAL)
        {
            var lOTE_IDParameter = lOTE_ID.HasValue ?
                new ObjectParameter("LOTE_ID", lOTE_ID) :
                new ObjectParameter("LOTE_ID", typeof(int));
    
            var lOTE_CODEParameter = lOTE_CODE != null ?
                new ObjectParameter("LOTE_CODE", lOTE_CODE) :
                new ObjectParameter("LOTE_CODE", typeof(string));
    
            var lOTE_AMOUNT_ITEMParameter = lOTE_AMOUNT_ITEM.HasValue ?
                new ObjectParameter("LOTE_AMOUNT_ITEM", lOTE_AMOUNT_ITEM) :
                new ObjectParameter("LOTE_AMOUNT_ITEM", typeof(int));
    
            var lOTE_ITEMTY_IDParameter = lOTE_ITEMTY_ID.HasValue ?
                new ObjectParameter("LOTE_ITEMTY_ID", lOTE_ITEMTY_ID) :
                new ObjectParameter("LOTE_ITEMTY_ID", typeof(int));
    
            var dIS_SHIP_IDParameter = dIS_SHIP_ID.HasValue ?
                new ObjectParameter("DIS_SHIP_ID", dIS_SHIP_ID) :
                new ObjectParameter("DIS_SHIP_ID", typeof(int));
    
            var dIS_AMOUNT_TOTALParameter = dIS_AMOUNT_TOTAL.HasValue ?
                new ObjectParameter("DIS_AMOUNT_TOTAL", dIS_AMOUNT_TOTAL) :
                new ObjectParameter("DIS_AMOUNT_TOTAL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveLote", lOTE_IDParameter, lOTE_CODEParameter, lOTE_AMOUNT_ITEMParameter, lOTE_ITEMTY_IDParameter, dIS_SHIP_IDParameter, dIS_AMOUNT_TOTALParameter);
        }
    
        public virtual int WEB_PostSaveReportObservation(Nullable<int> rPTOBS_ID, string rPTOBS_OBSERVATION, Nullable<int> rPTOBS_ID_CUS, Nullable<int> rPTOBS_ID_SHIP)
        {
            var rPTOBS_IDParameter = rPTOBS_ID.HasValue ?
                new ObjectParameter("RPTOBS_ID", rPTOBS_ID) :
                new ObjectParameter("RPTOBS_ID", typeof(int));
    
            var rPTOBS_OBSERVATIONParameter = rPTOBS_OBSERVATION != null ?
                new ObjectParameter("RPTOBS_OBSERVATION", rPTOBS_OBSERVATION) :
                new ObjectParameter("RPTOBS_OBSERVATION", typeof(string));
    
            var rPTOBS_ID_CUSParameter = rPTOBS_ID_CUS.HasValue ?
                new ObjectParameter("RPTOBS_ID_CUS", rPTOBS_ID_CUS) :
                new ObjectParameter("RPTOBS_ID_CUS", typeof(int));
    
            var rPTOBS_ID_SHIPParameter = rPTOBS_ID_SHIP.HasValue ?
                new ObjectParameter("RPTOBS_ID_SHIP", rPTOBS_ID_SHIP) :
                new ObjectParameter("RPTOBS_ID_SHIP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveReportObservation", rPTOBS_IDParameter, rPTOBS_OBSERVATIONParameter, rPTOBS_ID_CUSParameter, rPTOBS_ID_SHIPParameter);
        }
    
        public virtual int WEB_PostSaveShipment(Nullable<int> sHIP_ID, string sHIP_CODE, Nullable<int> cUS_ID, string sHIP_TOTAL_ITEMS, Nullable<int> iTEMTY_ID, Nullable<int> cONTY_ID, Nullable<int> sHIP_AMOUNT_CONTAINER, Nullable<System.DateTime> sHIP_DATE_SCHEDULED)
        {
            var sHIP_IDParameter = sHIP_ID.HasValue ?
                new ObjectParameter("SHIP_ID", sHIP_ID) :
                new ObjectParameter("SHIP_ID", typeof(int));
    
            var sHIP_CODEParameter = sHIP_CODE != null ?
                new ObjectParameter("SHIP_CODE", sHIP_CODE) :
                new ObjectParameter("SHIP_CODE", typeof(string));
    
            var cUS_IDParameter = cUS_ID.HasValue ?
                new ObjectParameter("CUS_ID", cUS_ID) :
                new ObjectParameter("CUS_ID", typeof(int));
    
            var sHIP_TOTAL_ITEMSParameter = sHIP_TOTAL_ITEMS != null ?
                new ObjectParameter("SHIP_TOTAL_ITEMS", sHIP_TOTAL_ITEMS) :
                new ObjectParameter("SHIP_TOTAL_ITEMS", typeof(string));
    
            var iTEMTY_IDParameter = iTEMTY_ID.HasValue ?
                new ObjectParameter("ITEMTY_ID", iTEMTY_ID) :
                new ObjectParameter("ITEMTY_ID", typeof(int));
    
            var cONTY_IDParameter = cONTY_ID.HasValue ?
                new ObjectParameter("CONTY_ID", cONTY_ID) :
                new ObjectParameter("CONTY_ID", typeof(int));
    
            var sHIP_AMOUNT_CONTAINERParameter = sHIP_AMOUNT_CONTAINER.HasValue ?
                new ObjectParameter("SHIP_AMOUNT_CONTAINER", sHIP_AMOUNT_CONTAINER) :
                new ObjectParameter("SHIP_AMOUNT_CONTAINER", typeof(int));
    
            var sHIP_DATE_SCHEDULEDParameter = sHIP_DATE_SCHEDULED.HasValue ?
                new ObjectParameter("SHIP_DATE_SCHEDULED", sHIP_DATE_SCHEDULED) :
                new ObjectParameter("SHIP_DATE_SCHEDULED", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveShipment", sHIP_IDParameter, sHIP_CODEParameter, cUS_IDParameter, sHIP_TOTAL_ITEMSParameter, iTEMTY_IDParameter, cONTY_IDParameter, sHIP_AMOUNT_CONTAINERParameter, sHIP_DATE_SCHEDULEDParameter);
        }
    
        public virtual int WEB_PostSaveShipmentDetails(Nullable<int> sHIP_ID, string sHIP_NRO_PER, Nullable<int> sHIP_PROD_ID, Nullable<System.DateTime> sHIP_DATE_SCHEDULED, string sHIP_BL, Nullable<int> sHIP_RPTSW_ID, Nullable<int> sHIP_TOTAL_ITEMS, Nullable<int> sHIP_CUS_ID, Nullable<int> sHIP_SHIPPER_ID, Nullable<int> sHIP_PRO_ID, Nullable<int> sHIP_RPTSI_ID, Nullable<int> sHIP_PORTD_ID, Nullable<int> sHIP_NAV_ID, string sHIP_BOOKING, string sHIP_RPTS_CLIENT, Nullable<int> sHIP_PORTL_ID, string sHIP_DESCRIPTION, string sHIP_OBS_GENERAL, string sHIP_OBS_REPORT)
        {
            var sHIP_IDParameter = sHIP_ID.HasValue ?
                new ObjectParameter("SHIP_ID", sHIP_ID) :
                new ObjectParameter("SHIP_ID", typeof(int));
    
            var sHIP_NRO_PERParameter = sHIP_NRO_PER != null ?
                new ObjectParameter("SHIP_NRO_PER", sHIP_NRO_PER) :
                new ObjectParameter("SHIP_NRO_PER", typeof(string));
    
            var sHIP_PROD_IDParameter = sHIP_PROD_ID.HasValue ?
                new ObjectParameter("SHIP_PROD_ID", sHIP_PROD_ID) :
                new ObjectParameter("SHIP_PROD_ID", typeof(int));
    
            var sHIP_DATE_SCHEDULEDParameter = sHIP_DATE_SCHEDULED.HasValue ?
                new ObjectParameter("SHIP_DATE_SCHEDULED", sHIP_DATE_SCHEDULED) :
                new ObjectParameter("SHIP_DATE_SCHEDULED", typeof(System.DateTime));
    
            var sHIP_BLParameter = sHIP_BL != null ?
                new ObjectParameter("SHIP_BL", sHIP_BL) :
                new ObjectParameter("SHIP_BL", typeof(string));
    
            var sHIP_RPTSW_IDParameter = sHIP_RPTSW_ID.HasValue ?
                new ObjectParameter("SHIP_RPTSW_ID", sHIP_RPTSW_ID) :
                new ObjectParameter("SHIP_RPTSW_ID", typeof(int));
    
            var sHIP_TOTAL_ITEMSParameter = sHIP_TOTAL_ITEMS.HasValue ?
                new ObjectParameter("SHIP_TOTAL_ITEMS", sHIP_TOTAL_ITEMS) :
                new ObjectParameter("SHIP_TOTAL_ITEMS", typeof(int));
    
            var sHIP_CUS_IDParameter = sHIP_CUS_ID.HasValue ?
                new ObjectParameter("SHIP_CUS_ID", sHIP_CUS_ID) :
                new ObjectParameter("SHIP_CUS_ID", typeof(int));
    
            var sHIP_SHIPPER_IDParameter = sHIP_SHIPPER_ID.HasValue ?
                new ObjectParameter("SHIP_SHIPPER_ID", sHIP_SHIPPER_ID) :
                new ObjectParameter("SHIP_SHIPPER_ID", typeof(int));
    
            var sHIP_PRO_IDParameter = sHIP_PRO_ID.HasValue ?
                new ObjectParameter("SHIP_PRO_ID", sHIP_PRO_ID) :
                new ObjectParameter("SHIP_PRO_ID", typeof(int));
    
            var sHIP_RPTSI_IDParameter = sHIP_RPTSI_ID.HasValue ?
                new ObjectParameter("SHIP_RPTSI_ID", sHIP_RPTSI_ID) :
                new ObjectParameter("SHIP_RPTSI_ID", typeof(int));
    
            var sHIP_PORTD_IDParameter = sHIP_PORTD_ID.HasValue ?
                new ObjectParameter("SHIP_PORTD_ID", sHIP_PORTD_ID) :
                new ObjectParameter("SHIP_PORTD_ID", typeof(int));
    
            var sHIP_NAV_IDParameter = sHIP_NAV_ID.HasValue ?
                new ObjectParameter("SHIP_NAV_ID", sHIP_NAV_ID) :
                new ObjectParameter("SHIP_NAV_ID", typeof(int));
    
            var sHIP_BOOKINGParameter = sHIP_BOOKING != null ?
                new ObjectParameter("SHIP_BOOKING", sHIP_BOOKING) :
                new ObjectParameter("SHIP_BOOKING", typeof(string));
    
            var sHIP_RPTS_CLIENTParameter = sHIP_RPTS_CLIENT != null ?
                new ObjectParameter("SHIP_RPTS_CLIENT", sHIP_RPTS_CLIENT) :
                new ObjectParameter("SHIP_RPTS_CLIENT", typeof(string));
    
            var sHIP_PORTL_IDParameter = sHIP_PORTL_ID.HasValue ?
                new ObjectParameter("SHIP_PORTL_ID", sHIP_PORTL_ID) :
                new ObjectParameter("SHIP_PORTL_ID", typeof(int));
    
            var sHIP_DESCRIPTIONParameter = sHIP_DESCRIPTION != null ?
                new ObjectParameter("SHIP_DESCRIPTION", sHIP_DESCRIPTION) :
                new ObjectParameter("SHIP_DESCRIPTION", typeof(string));
    
            var sHIP_OBS_GENERALParameter = sHIP_OBS_GENERAL != null ?
                new ObjectParameter("SHIP_OBS_GENERAL", sHIP_OBS_GENERAL) :
                new ObjectParameter("SHIP_OBS_GENERAL", typeof(string));
    
            var sHIP_OBS_REPORTParameter = sHIP_OBS_REPORT != null ?
                new ObjectParameter("SHIP_OBS_REPORT", sHIP_OBS_REPORT) :
                new ObjectParameter("SHIP_OBS_REPORT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveShipmentDetails", sHIP_IDParameter, sHIP_NRO_PERParameter, sHIP_PROD_IDParameter, sHIP_DATE_SCHEDULEDParameter, sHIP_BLParameter, sHIP_RPTSW_IDParameter, sHIP_TOTAL_ITEMSParameter, sHIP_CUS_IDParameter, sHIP_SHIPPER_IDParameter, sHIP_PRO_IDParameter, sHIP_RPTSI_IDParameter, sHIP_PORTD_IDParameter, sHIP_NAV_IDParameter, sHIP_BOOKINGParameter, sHIP_RPTS_CLIENTParameter, sHIP_PORTL_IDParameter, sHIP_DESCRIPTIONParameter, sHIP_OBS_GENERALParameter, sHIP_OBS_REPORTParameter);
        }
    
        public virtual int WEB_PostSaveShipmentReference(Nullable<int> sHIP_ID, string sHIP_REFERENCE)
        {
            var sHIP_IDParameter = sHIP_ID.HasValue ?
                new ObjectParameter("SHIP_ID", sHIP_ID) :
                new ObjectParameter("SHIP_ID", typeof(int));
    
            var sHIP_REFERENCEParameter = sHIP_REFERENCE != null ?
                new ObjectParameter("SHIP_REFERENCE", sHIP_REFERENCE) :
                new ObjectParameter("SHIP_REFERENCE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveShipmentReference", sHIP_IDParameter, sHIP_REFERENCEParameter);
        }
    
        public virtual int WEB_PostSaveUser(Nullable<int> uSER_ID, string uSER_NAME, string uSER_LASTNAME, string uSER_EMAIL, string uSER_PASSWORD, string uSER_DNI, Nullable<System.DateTime> uSER_BIRTHDATE, string uSER_MOB_PHONE, string uSER_PHONE, Nullable<int> uSER_ROL_ID)
        {
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(int));
    
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var uSER_LASTNAMEParameter = uSER_LASTNAME != null ?
                new ObjectParameter("USER_LASTNAME", uSER_LASTNAME) :
                new ObjectParameter("USER_LASTNAME", typeof(string));
    
            var uSER_EMAILParameter = uSER_EMAIL != null ?
                new ObjectParameter("USER_EMAIL", uSER_EMAIL) :
                new ObjectParameter("USER_EMAIL", typeof(string));
    
            var uSER_PASSWORDParameter = uSER_PASSWORD != null ?
                new ObjectParameter("USER_PASSWORD", uSER_PASSWORD) :
                new ObjectParameter("USER_PASSWORD", typeof(string));
    
            var uSER_DNIParameter = uSER_DNI != null ?
                new ObjectParameter("USER_DNI", uSER_DNI) :
                new ObjectParameter("USER_DNI", typeof(string));
    
            var uSER_BIRTHDATEParameter = uSER_BIRTHDATE.HasValue ?
                new ObjectParameter("USER_BIRTHDATE", uSER_BIRTHDATE) :
                new ObjectParameter("USER_BIRTHDATE", typeof(System.DateTime));
    
            var uSER_MOB_PHONEParameter = uSER_MOB_PHONE != null ?
                new ObjectParameter("USER_MOB_PHONE", uSER_MOB_PHONE) :
                new ObjectParameter("USER_MOB_PHONE", typeof(string));
    
            var uSER_PHONEParameter = uSER_PHONE != null ?
                new ObjectParameter("USER_PHONE", uSER_PHONE) :
                new ObjectParameter("USER_PHONE", typeof(string));
    
            var uSER_ROL_IDParameter = uSER_ROL_ID.HasValue ?
                new ObjectParameter("USER_ROL_ID", uSER_ROL_ID) :
                new ObjectParameter("USER_ROL_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_PostSaveUser", uSER_IDParameter, uSER_NAMEParameter, uSER_LASTNAMEParameter, uSER_EMAILParameter, uSER_PASSWORDParameter, uSER_DNIParameter, uSER_BIRTHDATEParameter, uSER_MOB_PHONEParameter, uSER_PHONEParameter, uSER_ROL_IDParameter);
        }
    
        public virtual ObjectResult<string> WEB_PostValidateLoginByAccountAndPassword(string uSER_EMAIL, string uSER_PASSWORD)
        {
            var uSER_EMAILParameter = uSER_EMAIL != null ?
                new ObjectParameter("USER_EMAIL", uSER_EMAIL) :
                new ObjectParameter("USER_EMAIL", typeof(string));
    
            var uSER_PASSWORDParameter = uSER_PASSWORD != null ?
                new ObjectParameter("USER_PASSWORD", uSER_PASSWORD) :
                new ObjectParameter("USER_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WEB_PostValidateLoginByAccountAndPassword", uSER_EMAILParameter, uSER_PASSWORDParameter);
        }
    }
}
